### ISSUE TITLE
Use release tags

### ISSUE THREAD

**Issue by rhtenhove** [NCSC-NL/taranis3#1]
Using release tags lets us know when a point on the master branch (which currently seems to be named 'release-3.4') has stable (enough) code.

See [here](https://github.com/NCSC-NL/taranis3/releases)

**Comment by markov2** [comment]
Of course, that's how it works.  Nothing was released since we started that archive. We do have a release since last night... still to be announced on various spots.

Our public repo will only contain the maintenance tracks for releases: therefore no 'master' branch.  We have a private repo for our development work.
