### ISSUE TITLE
Main.js - Minor typo or needed?

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#46]
https://github.com/NCSC-NL/taranis3/blob/922696da460d4213fed4dbec67eda5f61ec6f6da/webinterface/include/js/main.js#L132

Removing this line seems to have no impact.  

"Correcting" it to ` .appendTo('#dialog'); ` results in empty ui-dialogs.

**Comment by markov2** [comment]
Really interesting case.  So: when jQuery fails to find the selected element in ``.appendTo()``, it will return the constructed object, but when it finds a place it does not.  The ``div`` with id ``dialog`` is on the main page (and seems not to be used).  I will remove the appendTo.

The bug was already present in Taranis 3.0.0, which started the git-repo 8 years ago.

**Comment by markov2** [comment]
I picked this up for mainstream 3.8: this is not important for a hotfix, so gets through the usual testing first.  Maintenance release 3.7.5 got released today.
